name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Typecheck
        run: yarn lint

      - name: Unit tests
        run: yarn test

      - name: Build library
        run: yarn build

      - name: Build example app
        run: yarn example:build
